name: CI
on:
  pull_request:
    paths:
      - ".github/workflows/ci.yml"
      - "recipes/**"
      - "docs/archive/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: purcell/setup-emacs@master
        with:
          version: 29.1
      - name: cache cask packages
        uses: actions/cache@v3
        id: cache-cask-packages
        with:
          path: .cask
          key: cache-cask-packages-000
      - name: cache cask executable
        uses: actions/cache@v3
        id: cache-cask-executable
        with:
          path: ~/.cask
          key: cache-cask-executable-000
      - uses: cask/setup-cask@master
        if: steps.cache-cask-executable.outputs.cache-hit != 'true'
        with:
          version: snapshot
      - name: Build recipes
        run: make build
      - name: Check that docs/archive is up-to-date
        id: check-changes
        run: |
          if [[ -n $(git status --porcelain docs/archive) ]]; then
            echo "ERROR: Changes detected in docs/archive. Please run `make all` to commit generated archive contents."
            exit 1
          fi
